services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "8080:80"
      - "81:81"
      - "8443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
